// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Logos: typeof import('./src/components/Logos.vue')['default']
    PricingAdvanced: typeof import('./src/components/PricingAdvanced.vue')['default']
    PricingBasic: typeof import('./src/components/PricingBasic.vue')['default']
    PricingWL: typeof import('./src/components/PricingWL.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Soon: typeof import('./src/components/soon.vue')['default']
    Stats: typeof import('./src/components/Stats.vue')['default']
  }
}
